### ISSUE TITLE
Admin side - Teachers - these two features are not working.

### ISSUE THREAD

**Issue by Rajar91221** [Rajar91221/Tutor-reach-QA-#126]
![image](https://user-images.githubusercontent.com/50227023/132192552-e9158a54-9448-4e94-83c4-877d4147bce2.png)

**Comment by Adiconquerors** [comment]
Moe,

Need you inputs on this.

Sending bulk emails/sms may prevent gateways.

which means sending number of messages per a given time-restricted in gateways.

Suppose sending 100 emails in one minute, may stop the process at serer level.

Presently we implemented it as cronjob.

@TutorReachAdmin

**Comment by Adiconquerors** [comment]
Fixed Bulk Messages Issue.

Video Call Settings Need Moe Attention.

@TutorReachAdmin

**Comment by TutorReachAdmin** [comment]
The video call settings was meant to be for zoom functionality but don't think it would be a. Easy task to take to apply on twilio... for now we can leave them disabled and put a tag coming soon
