### ISSUE TITLE
Admin side - teachers - Top tutors data is not showing.

### ISSUE THREAD

**Issue by Rajar91221** [Rajar91221/Tutor-reach-QA-#130]
![image](https://user-images.githubusercontent.com/50227023/132196784-11da69cf-456b-4ed2-bd52-ee95259c0922.png)

**Comment by Adiconquerors** [comment]
![image](https://user-images.githubusercontent.com/75356516/133441924-b1f493f6-c2a4-4e53-9a90-56228b65d38c.png)


Moe need your attention. What is response here?

@TutorReachAdmin

**Comment by Adiconquerors** [comment]
@TutorReachAdmin 

Any update on this?

**Comment by Rajar91221** [comment]
@TutorReachAdmin 

Any update on this Moe?

**Comment by TutorReachAdmin** [comment]
A form of statistics to measure how fast they accept lessons so difference between booking time and accepting time average for that tutor with all his students cross all their lessons 

It's a statistic for now until after launch right "Coming Soon"
