### ISSUE TITLE
Admin side - tutors - View application - click on ID proof - Showing error.

### ISSUE THREAD

**Issue by Rajar91221** [Rajar91221/Tutor-reach-QA-#131]
![image](https://user-images.githubusercontent.com/50227023/132197196-7c589d4f-1fc4-41df-be7e-2c8731ec2328.png)
![image](https://user-images.githubusercontent.com/50227023/132197223-da37a7d7-1d5f-4a8e-a0e6-b270257396ef.png)

**Comment by samuel7895** [comment]
@Rajar91221 

When we copy the image URL in another browser where user is not logged it.
We will get this screen Keep APP_DEBUG=false not avoid it.
![Screenshot (52)](https://user-images.githubusercontent.com/88888961/132955707-d663381b-479b-4de5-b14d-1540cf1ea464.png)

**Comment by Adiconquerors** [comment]
If the file not exists it will redirect to the admin page. Otherwise it will display image on the browser

**Comment by Rajar91221** [comment]
@TutorReachAdmin 

Moe, Images are not uploading on the server. Can you please check once?

**Comment by Adiconquerors** [comment]
It broke when we change our server to aws
