### ISSUE TITLE
Admin side - tutors - I have rejected all details for newly registed tutors - then how can they upload again and what to do if admin will approve that tutor?

### ISSUE THREAD

**Issue by Rajar91221** [Rajar91221/Tutor-reach-QA-#132]
![image](https://user-images.githubusercontent.com/50227023/132198235-ad8c7606-c65a-4c77-99aa-cc342efe1696.png)

**Comment by Rajar91221** [comment]
@TutorReachAdmin 

1.Lessons -> Experienced Errors.2.

2. tutors - I have rejected all details for newly registered tutors - then how can they upload again and what to do if the admin will approve that tutor?

3. Currency Conversions.

**Comment by Adiconquerors** [comment]
@TutorReachAdmin 

Moe any update on this?

**Comment by TutorReachAdmin** [comment]
If tutor updates or new registration is rejected the tutor should be notified and admin should leave a message in the comment box to explain why. The tutor then able to update their profile as usual and press update to submit again... inside the profile update page we must show a message show changes are pending approval and so on... this is for new registration and for updates that we track

**Comment by TutorReachAdmin** [comment]
@Rajar91221

**Comment by AdminTutorreach** [comment]
@Adiconquerors @Rajar91221 I replied to this 2 days ago

**Comment by samuel7895** [comment]
@TutorReachAdmin 

Moe Can you provide info on this

1.Lessons -> Experienced Errors.

 2. Currency Conversions.
    https://github.com/Rajar91221/Tutor-reach-QA-/issues/37

**Comment by TutorReachAdmin** [comment]
Experienced errors any student or tutor who faces 500 error or any Laravel error can we log their username and error details please this section is a log of system errors
