### ISSUE TITLE
Admin side - Settings  - I have deselected all action  but after registration its asking approval from admin side.

### ISSUE THREAD

**Issue by Rajar91221** [Rajar91221/Tutor-reach-QA-#133]
![image](https://user-images.githubusercontent.com/50227023/132199197-456ec507-ab85-4ba1-a679-aa58cb63373a.png)
![image](https://user-images.githubusercontent.com/50227023/132199234-01934815-3918-43e2-adbd-f3c4037b5692.png)

**Comment by samuel7895** [comment]
@Rajar91221 

This Option Wont apply at the time of First Time Registration of Tutor.
