### ISSUE TITLE
Admin side i have enabled All tutors to create custom discount package. But in tutor side its not reflecting.

### ISSUE THREAD

**Issue by Rajar91221** [Rajar91221/Tutor-reach-QA-#135]
![image](https://user-images.githubusercontent.com/50227023/132202968-40f865bb-ed9d-43ee-b2c2-681c9360a4e7.png)

**Comment by samuel7895** [comment]
@TutorReachAdmin 

All tutors to create custom discount packages.Explain this Moe.

**Comment by TutorReachAdmin** [comment]
This is our packages option we have... I believe it's already implemented just need to be able to enable and disable

**Comment by Adiconquerors** [comment]
Fixed
