### ISSUE TITLE
Admin side - Finance - These three features are not working.

### ISSUE THREAD

**Issue by Rajar91221** [Rajar91221/Tutor-reach-QA-#138]
![image](https://user-images.githubusercontent.com/50227023/132204088-95fb80cf-d393-4a89-bc8c-7ac078c105db.png)

**Comment by samuel7895** [comment]
@Rajar91221 
@TutorReachAdmin 

Not in spec hiding it.

**Comment by TutorReachAdmin** [comment]
No don't hide it how is the student going to get the refund. Please let's use logic and common sense, I understand there's a lot of pressure to finish but doing take an individual action like this without consulting or thinking of the process for the platform.

**Comment by Adiconquerors** [comment]
These are new features to be implemented.

**Comment by Adiconquerors** [comment]
Displaying coming soon message as of now
