### ISSUE TITLE
Admin side -  Finance - All fields - Filters are not working.

### ISSUE THREAD

**Issue by Rajar91221** [Rajar91221/Tutor-reach-QA-#140]
![image](https://user-images.githubusercontent.com/50227023/132204377-41a1758b-4708-4dc9-9398-2ef591c38e57.png)

**Comment by Rajar91221** [comment]
![image](https://user-images.githubusercontent.com/50227023/133078892-88664eba-ef22-4f7c-8edd-38e9669b57ac.png)
 Some filters are not working properly.

**Comment by Adiconquerors** [comment]
Fixed
