### ISSUE TITLE
Admin Side - tutor settings - These two features functionality is not working.

### ISSUE THREAD

**Issue by Rajar91221** [Rajar91221/Tutor-reach-QA-#145]
![image](https://user-images.githubusercontent.com/50227023/132208559-5c73652d-dc9e-4843-a4bc-8cad75d3c615.png)

**Comment by samuel7895** [comment]
@TutorReachAdmin 

Max Number of Lessons Per Day: elaborate it? and where to restrict it?

**Comment by TutorReachAdmin** [comment]
![image](https://user-images.githubusercontent.com/77559514/132857851-8d114835-d512-4944-b98b-51b6453a8c24.png)
Disable the input buttons for now and make them empty but leave them there wirh label (Not Available) as they are not urgent and not important for MVP

**Comment by Adiconquerors** [comment]
Hi Moe,

Please explain 'Max Number of Lessons Per Day' option so that we will close this issue.

We are planning to close all.

Please explain.

Thanks,
- Adi

**Comment by Adiconquerors** [comment]
Hi Moe,

Any update on this?

**Comment by TutorReachAdmin** [comment]
@Adiconquerors please ignore my previous reply as i misunderstood the purpose of this because of the label name. I will explain this in a comment here properly

**Comment by TutorReachAdmin** [comment]
![image](https://user-images.githubusercontent.com/77559514/133397533-79388e29-77af-4e23-8d84-6f1f0a6311e1.png)

1. Max Number of Subjects To Teach - This is to limit amount of subject a tutor can be listed in.
2. Max Number of Lessons Per Day - this is to limit the amount of lessons a tutor can do a day.
3. Number of Hours to Auto-Cancel Lesson (mins) - Auto cancel a lesson if tutor not accepted the booking yet.
4. Number of Hours to Auto-Confirm Lesson (mins) - this label should be to 'auto approve' and should be in hours... it's referring to once lesson is complete and both parties attended how many hours for student to either confirm or request reschedule or request a cancellation or raise a complaint about.

**Comment by TutorReachAdmin** [comment]
@Rajar91221 @samuel7895 @Adiconquerors @Nag3ndra

**Comment by samuel7895** [comment]
@TutorReachAdmin 

Updated 1 , 3(Cron Job) , 4(Cron Job)
2. Max Number of Lessons Per Day - this is to limit the number of lessons a tutor can do a day.

**Question**
At What Place we are going to restrict the tutor or implement this at an availability or do we internally do it from the backend while showing the timeslots to the user.

**Comment by Adiconquerors** [comment]
@TutorReachAdmin 

Moe,

Any update on this?

**Comment by Rajar91221** [comment]
We are showing the first 5 slots if the admin will select 5 slots per day.
