### ISSUE TITLE
While registering - there is no resume option - in admin side resume health check is showing uploaded.

### ISSUE THREAD

**Issue by Rajar91221** [Rajar91221/Tutor-reach-QA-#18]
![image](https://user-images.githubusercontent.com/50227023/132089451-a5d12988-2203-4960-804e-f15b1df04b28.png)

**Comment by samuel7895** [comment]
![Screenshot(6)](https://user-images.githubusercontent.com/88888961/132445634-59468a88-1e39-4c73-9e44-f2cbd5598999.png)
We are taking all the required mandatory fields of tutor teaching at the time of resume.
