### ISSUE TITLE
New student... topped up wallet but can't use it to pay

### ISSUE THREAD

**Issue by TutorReachAdmin** [Rajar91221/Tutor-reach-QA-#223]
![image](https://user-images.githubusercontent.com/77559514/133720482-ae327084-9b8f-4d5c-9511-0bf663297de1.png)

I registered a new student and added money to wallet but can't pay with wallet... i have ti hard refresh

**Comment by samuel7895** [comment]
![2021-09-17](https://user-images.githubusercontent.com/88888961/133873247-28c2efad-008c-43b4-89bc-f908fcefadd2.png)

Working In Sandbox
