### ISSUE TITLE
dahsboard is in accurate and why do we show options for cancelled lessons!!!???.... Validation work is very poor!

### ISSUE THREAD

**Issue by AdminTutorreach** [Rajar91221/Tutor-reach-QA-#242]
![image](https://user-images.githubusercontent.com/87555775/134098346-8632d3ba-7596-436e-bf6b-de43523407d7.png)

**Comment by Rajar91221** [comment]
student side- dashboard- direct cancellation - it will show 4 lessons but it has only 2
