### ISSUE TITLE
Tutor side -We are not using these option in application.

### ISSUE THREAD

**Issue by Rajar91221** [Rajar91221/Tutor-reach-QA-#26]
![image](https://user-images.githubusercontent.com/50227023/132090058-37df13be-8f99-4b78-b9cc-f8354db1f8d7.png)

**Comment by TutorReachAdmin** [comment]
this is just to store data not to be used yet but make sure they are saving and UI is fixed

**Comment by Rajar91221** [comment]
Keep it as 9 num validation only.
