### ISSUE TITLE
Admin side - Click on Users - Its showing validation.

### ISSUE THREAD

**Issue by Rajar91221** [Rajar91221/Tutor-reach-QA-#93]
![image](https://user-images.githubusercontent.com/50227023/132168549-3e4ab929-9a97-4e86-8760-58f90be2ac8c.png)
Video link for refenrence: https://www.loom.com/share/c21a3b48b4514540825b19d15b2bf824?focus_title=1&muted=1&from_recorder=1

**Comment by samuel7895** [comment]
@Adiconquerors Sir

We used (blur) for email validation hope it causing the issue

**Comment by Adiconquerors** [comment]
Yes Samuel. Iam removing (blue) event. It will validate on server side
